export const SET_BOOKING = 'SET_BOOKING';
export const SET_BOOKINGS = 'SET_BOOKINGS';
export const SET_BOOKING_WITH_FILTER = 'SET_BOOKING_WITH_FILTER';
export const FAILED_UPDATE_BOOKING = 'FAILED_UPDATE_BOOKING';
export const FAILED_GET_BOOKINGS = 'FAILED_GET_BOOKINGS';
export const SET_MAPPEDBOOKINGS = 'SET_MAPPEDBOOKINGS';
export const SET_USER_DATE_FILTER_FIELD = 'SET_USER_DATE_FILTER_FIELD';
export const FAILED_GET_USER_DATE_FILTER_FIELD = 'FAILED_GET_USER_DATE_FILTER_FIELD';
