export const SET_BOOKINGLINES = 'SET_BOOKINGLINES';
export const FAILED_GET_BOOKINGLINES = 'FAILED_GET_BOOKINGLINES';
export const SUCCESS_CREATE_BOOKING_LINE = 'SUCCESS_CREATE_BOOKING_LINE';
export const FAILED_CREATE_BOOKING_LINE = 'FAILED_CREATE_BOOKING_LINE';
export const SUCCESS_UPDATE_BOOKING_LINE = 'SUCCESS_UPDATE_BOOKING_LINE';
export const FAILED_UPDATE_BOOKING_LINE = 'FAILED_UPDATE_BOOKING_LINE';
