export const SET_BOOKING = 'SET_BOOKING';
export const SET_BOOKINGS = 'SET_BOOKINGS';
export const SET_BOOKING_WITH_FILTER = 'SET_BOOKING_WITH_FILTER';
export const FAILED_UPDATE_BOOKING = 'FAILED_UPDATE_BOOKING';
export const FAILED_GET_BOOKINGS = 'FAILED_GET_BOOKINGS';
export const SET_MAPPEDBOOKINGS = 'SET_MAPPEDBOOKINGS';
export const SET_USER_DATE_FILTER_FIELD = 'SET_USER_DATE_FILTER_FIELD';
export const FAILED_GET_USER_DATE_FILTER_FIELD = 'FAILED_GET_USER_DATE_FILTER_FIELD';
export const BOOK_SUCCESS = 'BOOK_SUCCESS';
export const BOOK_FAILED = 'BOOK_FAILED';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const GET_LABEL_FAILED = 'GET_LABEL_FAILED';
export const SET_SUBURB = 'SET_SUBURB';
export const SET_STATE = 'SET_STATE';
export const SET_POSTALCODE = 'SET_POSTALCODE';
export const FAILED_GET_SUBURBS = 'FAILED_GET_SUBURBS';
export const SET_POSTALCODE_DE = 'SET_POSTALCODE_DE';
export const SET_SUBURB_DE = 'SET_SUBURB_DE';
export const SET_STATE_DE = 'SET_STATE_DE';
export const FAILED_GET_SUBURBS_DE = 'FAILED_GET_SUBURBS_DE';
export const SET_ATTACHMENTS = 'SET_ATTACHMENTS_DE';
export const FAILED_GET_ATTACHMENTS = 'FAILED_GET_ATTACHMENTS_DE';


