export const SUCCESS_GET_ALL_CLIENTS = 'SUCCESS_GET_ALL_CLIENTS';
export const FAILED_GET_ALL_CLIENTS = 'FAILED_GET_ALL_CLIENTS';
export const SUCCESS_CREATE_CLIENT = 'SUCCESS_CREATE_CLIENT';
export const FAILED_CREATE_CLIENT = 'FAILED_CREATE_CLIENT';
export const SUCCESS_UPDATE_CLIENT = 'SUCCESS_UPDATE_CLIENT';
export const FAILED_UPDATE_CLIENT = 'FAILED_UPDATE_CLIENT';
export const SUCCESS_GET_CLIENT = 'SUCCESS_GET_CLIENT';
export const FAILED_GET_CLIENT = 'FAILED_GET_CLIENT';