export const SUCCESS_GET_FP_COSTS = 'SUCCESS_GET_FP_COSTS';
export const FAILED_GET_FP_COSTS = 'FAILED_GET_FP_COSTS';
export const SUCCESS_GET_COST_OPTIONS = 'SUCCESS_GET_COST_OPTIONS';
export const FAILED_GET_COST_OPTIONS = 'FAILED_GET_COST_OPTIONS';
export const SUCCESS_GET_COST_OPTION_MAPS = 'SUCCESS_GET_COST_OPTION_MAPS';
export const FAILED_GET_COST_OPTION_MAPS = 'FAILED_GET_COST_OPTION_MAPS';
export const SUCCESS_GET_BOOKING_COST_OPTIONS = 'SUCCESS_GET_BOOKING_COST_OPTIONS';
export const FAILED_GET_BOOKING_COST_OPTIONS = 'FAILED_GET_BOOKING_COST_OPTIONS';
