export const SUCCESS_GET_PACKAGETYPES = 'SUCCESS_GET_PACKAGETYPES';
export const FAILED_GET_PACKAGETYPES = 'FAILED_GET_PACKAGETYPES';
export const SUCCESS_GET_ALL_BOOKING_STATUS = 'SUCCESS_GET_ALL_BOOKING_STATUS';
export const FAILED_GET_ALL_BOOKING_STATUS = 'FAILED_GET_ALL_BOOKING_STATUS';
export const SUCCESS_GET_BOOKING_STATUS_HISTORY = 'SUCCESS_GET_BOOKING_STATUS_HISTORY';
export const FAILED_GET_BOOKING_STATUS_HISTORY = 'FAILED_GET_BOOKING_STATUS_HISTORY';
export const SUCCESS_SAVE_STATUS_STATUS = 'SUCCESS_SAVE_STATUS_STATUS';
export const FAILED_SAVE_STATUS_STATUS = 'FAILED_SAVE_STATUS_STATUS';
