export const SUCCESS_GET_PACKAGETYPES = 'SUCCESS_GET_PACKAGETYPES';
export const FAILED_GET_PACKAGETYPES = 'FAILED_GET_PACKAGETYPES';
export const SUCCESS_GET_ALL_BOOKING_STATUS = 'SUCCESS_GET_ALL_BOOKING_STATUS';
export const FAILED_GET_ALL_BOOKING_STATUS = 'FAILED_GET_ALL_BOOKING_STATUS';
